-- Run this file once in Supabase Dashboard > SQL Editor.
-- It creates the quiz results table and allows anonymous quiz submissions.

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  first_name text not null check (char_length(first_name) between 1 and 100),
  last_name text not null check (char_length(last_name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 320),
  cube_number text not null check (char_length(cube_number) between 1 and 100),
  score integer not null check (score between 0 and 100),
  correct_count integer not null check (correct_count between 0 and 25),
  wrong_count integer not null check (wrong_count between 0 and 25),
  answers jsonb not null,
  language text not null check (language in ('tr','en')),
  completed_at timestamptz not null default now(),
  constraint quiz_result_totals check (correct_count + wrong_count = 25 and score between 0 and correct_count * 4)
);

alter table public.quiz_results enable row level security;

revoke all on table public.quiz_results from anon, authenticated;
grant insert on table public.quiz_results to anon, authenticated;
grant usage, select on sequence public.quiz_results_id_seq to anon, authenticated;

drop policy if exists "Anyone can submit a quiz result" on public.quiz_results;
create policy "Anyone can submit a quiz result"
on public.quiz_results
for insert
to anon, authenticated
with check (
    score between 0 and 100
  and correct_count between 0 and 25
  and wrong_count between 0 and 25
  and correct_count + wrong_count = 25
    and score <= correct_count * 4
  and jsonb_typeof(answers) = 'array'
  and jsonb_array_length(answers) = 25
);

-- No SELECT policy is created: visitors can submit results but cannot read them.
-- View results securely from the Supabase Table Editor.
